### ISSUE TITLE
user journey #4 - Buy In Person

### ISSUE THREAD

**Issue by MarlenAw** [FACN3/cryptoCoin#11]
After the user has logged in, he can press "Buy In Person" and that would take him to a page where all the sellers have posted their deals/offers. 

- [X] Posts - Rendering the posts from the Database/JSON file to "Buy In Person" page.
- [X] Setting up the database to store users and posts.
- [X] Setting up the server.
- [ ] Authentication
- [ ] Add/Edits posts for each user
- [ ] Private chat
